### ISSUE TITLE
Proposal: work with any plug-based app

### ISSUE THREAD

**Issue by joshrieken** [boydm/phoenix_integration#1]
First of all, I love this! Thanks for making it. It fills a Phoenix need that's been there for awhile.

I'd like to propose perhaps extracting this out to another package that would work with any plug-based application, similar to how [capybara](https://github.com/jnicklas/capybara) in Ruby land works with any Rack-based app.

A prerequisite to this would involve making a phoenix-agnostic alternative to Phoenix.ConnTest, which I've been considering creating. Perhaps this could also eventually replace Phoenix.ConnTest within Phoenix.

Do you have any thoughts on this?

**Comment by boydm** [comment]
Thanks! I appreciate the feedback.

The only functions it uses in Phoenix.ConnTest are get/post/put/patch/delete. Those look pretty phoenix specific, but as long as there is some equivalent mapping to other plug based tools, then bringing these tests over would be pretty easy. assert_response is already agnostic, it is just the follow_\* type functions that need some way to "hit" the server.

What sort of non-Phoenix applications are you thinking of?

**Comment by joshrieken** [comment]
Thanks for replying, @boydm.

After some thought, my real desire is for a robust, standardized testing interface for plug connections. This could be accomplished via a behaviour and adapters written for various frameworks/scenarious (Phoenix would be the first).

This would open the door for an integration testing framework, like this one, that works with anything that conforms to the behaviour: Phoenix, a simple API that just uses Plug.Router, and other things that haven't been invented yet.

This desire is born not out of a production need, and is merely a curiosity.

Thanks for your time. If and when I get around to creating this behaviour with an example Phoenix adapter, I'll report back.
