### ISSUE TITLE
Update follow_link for phoenix_html 2.10

### ISSUE THREAD

**Issue by waiting-for-dev** [boydm/phoenix_integration#12]
Since phoenix_html 2.10, `link` with `:method` option other than get does not generate an inline form anymore, so `follow_link` function should be updated to work with it.

This is the commit which introduced the change:

https://github.com/phoenixframework/phoenix_html/commit/0e017552cf2f782885192e892d38ecb5142f8e36

**Comment by boydm** [comment]
I'll try to take a look at it over the weekend...

**Comment by waiting-for-dev** [comment]
No hurry, I have a `skip` for now :) In some weeks I'll be more free to try to submit PR's instead of just opening issues ;)

**Comment by boydm** [comment]
This should be fixed in master.

**Comment by waiting-for-dev** [comment]
Great, thanks :)
