### ISSUE TITLE
v0.5.0 release tag

### ISSUE THREAD

**Issue by wojtekmach** [boydm/phoenix_integration#21]
Hi, thanks for this project, I wanted to use browser-less acceptance framework for a long time and I didn't know it was there all along!

I was trying to get to code from [docs](https://hexdocs.pm/phoenix_integration/PhoenixIntegration.Assertions.html#assert_response/2) but it 404s because there's no v0.5.0 tag on GitHub. It would be great if you could add that in case anyone else runs into this problem in the future.

<details>
<summary>shameless plug</summary>

I've built a tool https://github.com/wojtekmach/shipit that is supposed to automate common steps in publishing a package. If this is something you'd consider using I'd appreciate any feedback!
</details>

**Comment by boydm** [comment]
Got it. Timing was good as I just pushed v0.5.1 with a bug fix. Published a tag for it.

I'll check out the shipit package.

Thanks!
