### ISSUE TITLE
Host lost during follow_redirect

### ISSUE THREAD

**Issue by mxgrn** [boydm/phoenix_integration#27]
I'm setting a host in the `setup` block like this:

```elixir
setup do
  conn = %{build_conn() | host: "foo.bar.dev"}
  %{conn: conn}
end
```

However, this seems to not be respected when I call `follow_redirect`. Is this a known issue?

Note: in a previous version of this lib there was a method called `preserve_host`, which now seems gone.

**Comment by boydm** [comment]
Hi! Sorry it's been a while. I'm in the phoenix_integration code now. Is this still an issue for you?

**Comment by mxgrn** [comment]
No worries. Yep, we're still using this library, so, it might come handy if it gets fixed. Thanks a bunch in any case!

**Comment by boydm** [comment]
Could you provide me some repo steps? I'll look at it in the morning (it is late here. going to bed...) and I just don't remember the context around `preserve_host`. A test that fails would be nice too, but I'll take more repo steps too...

**Comment by boydm** [comment]
Apologies for leaving this open for a bit.

I want to get the other updates out and this one will require  me to do a bunch of setup in order to wrap my head around it (I'm in the middle of a rather massive project in C, so my headspace just isn't there right now...)

**Comment by mxgrn** [comment]
No problem. I'll reopen it when I have time to get back to it, and will try to write a test.
