### ISSUE TITLE
Floki v0.24.0 emits deprecations

### ISSUE THREAD

**Issue by ZombieHarvester** [boydm/phoenix_integration#29]
https://github.com/philss/floki version 0.24.0 emits deprecations on PhoenixIntegration v0.6

```
warning: deprecation: parse the HTML with parse_document or parse_fragment before using find/2
  lib/floki.ex:170: Floki.find/2
  (phoenix_integration) lib/phoenix_integration/requests.ex:675: PhoenixIntegration.Requests.find_html_link/3
  (phoenix_integration) lib/phoenix_integration/requests.ex:189: PhoenixIntegration.Requests.click_link/3
  (phoenix_integration) lib/phoenix_integration/requests.ex:251: PhoenixIntegration.Requests.follow_link/3
...
```

**Comment by jonasschmidt** [comment]
We also had to lock `floki` at `< 0.24.0` to prevent those warnings.

**Comment by boydm** [comment]
How important is this to you guys? Also, is there a proposed fix? I'm going to roll an update to 0.6.1 to deal with the is_struct conflict with Elixir v1.10. If there is a preferred thing to do here, I'll try to get it in...

**Comment by boydm** [comment]
Hey guys. Fixing this to get rid of the deprecations may mean taking a requirement on a newer version of Floki.

Any objections?

**Comment by boydm** [comment]
Confirmed. Fixing it will require >= Floki 0.24.0

**Comment by boydm** [comment]
The fix is in the floki_update branch. I'll leave it there for a day, then merge it in if anybody wants to take a look.

**Comment by ZombieHarvester** [comment]
Looks good! Thanks.

**Comment by boydm** [comment]
OK. This is merged into master

**Comment by ZombieHarvester** [comment]
Floki released 0.25.0 🤷‍♂️
This time no braking changes, shouldn't be a problem to upgrade

**Comment by boydm** [comment]
I'm going to require >= 0.24.0 as that is the minimum version that it all works for. 0.25 is good too.

**Comment by ZombieHarvester** [comment]
currently it requires strict "0.24.0"

**Comment by boydm** [comment]
My bad. Should have been ">= 0.24.0" Fixing now

**Comment by ZombieHarvester** [comment]
Awesome, thanks

**Comment by boydm** [comment]
Fixed, and I just pushed 0.7.0 to hex.

**Comment by ZombieHarvester** [comment]
Perfect. Thanks for the great package, so much better than built in controller testing or wallaby/poison

**Comment by boydm** [comment]
Thanks! I appreciate that!

I'm always a fan of "simpler is better"

**Comment by ZombieHarvester** [comment]
simpler and FASTER

**Comment by boydm** [comment]
:-)

One usually leads to the other. Can't wait to show off the big C project I'm working on. Definitely follows that line of thinking.
