### ISSUE TITLE
follow_form/3 fails when using email_input/HTML input of type "email" in v0.8

### ISSUE THREAD

**Issue by tuacker** [boydm/phoenix_integration#36]
Given the following form and test:

```elixir
# Form ----
<%= form_for @changeset, @action, fn f -> %>

  <%= label f, :email %>
  <%= email_input f, :email %>
  <%= error_tag f, :email %>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

# Test ----
test "create user", %{conn: conn} do
    get(conn, Routes.user_path(conn, :new))
    |> follow_form(%{user: %{email: "email@email.com"}})
end
```

Will fail with this error:
```
Error: You tried to set the value of a tag that isn't in the form.
Path tried: [:user, :email]
Is this a typo?: :user
Your value: "email@email.com"
Form action: "/users"
```

Changing the `email_input` in the form to a normal `text_input` and running the test again works. 

`email_input` is just a normal Phoenix tag that sets the `type` of the HTML input to `"email"` instead of `"text"`.

**Comment by boydm** [comment]
Hi @marick. Would you be willing to take a look at this one? Pretty sure it is in the new form parser. We should make confirm that password fields work too why we're at it.

Sounds like a quick turn around on a 0.8.1 release...

**Comment by marick** [comment]
Embarrassing. I ignored that small, still voice that told me not to replace `def f(_)` with `def f("text")`. After 43 years of programming, you'd think that small still voice would learn to **speak up**.

**Comment by marick** [comment]
Note I now confirm that all these types are included in the generated tree:

```elixir
      %{date: "",
        datetime_local: "",
        email: "",
        file: "",
        hidden: "",
        month: "",
        number: "",
        password: "",
        photo: "",
        range: "",
        search: "",
        tel: "",
        text: "",
        time: "",
        url: "",
        week: "",
        datetime: ""
      }}
```

**Comment by tuacker** [comment]
Ran my tests against #37 changes and its working as expected 👍

**Comment by boydm** [comment]
Great!

My computer is in the repair shop for a few hours. ☹️ I’ll merge and roll the update once I’m online again...
