### ISSUE TITLE
Another case of a broken array of checkboxes

### ISSUE THREAD

**Issue by rafaelgaspar** [boydm/phoenix_integration#45]
Hi,

First of all, thanks for this awesome library, we use it on a few projects and it helps a lot, also thanks @marick for the amazing work refactoring the way it parses the form tree.

I have all tests green on `0.7.0` and the application works as intended, but when updating to `0.8.2` I started getting the following error:

```
Error: You are combining list and scalar values.
The value you want to use is a list:
    ["ci"]
But the name of the tag doesn't end in `[]`:
    "ab_test[environments]"
Form action: "/manage/config/games/VGIIQQZCKNSNVRYN/ab_tests"
```

The form itself has this rendered HTML:

```html
<div>
  <input id="ab_test_environments" name="ab_test[environments]" type="hidden" value="" />
  <label class="checkbox-inline">
    <input data-persisted="false" name="ab_test[environments][]" type="checkbox" value="ci" checked="" />
    Ci
  </label>
  <label class="checkbox-inline">
    <input data-persisted="false" name="ab_test[environments][]" type="checkbox" value="staging" checked="" />
    Staging
  </label>
  <label class="checkbox-inline">
    <input data-persisted="false" name="ab_test[environments][]" type="checkbox" value="production" />
    Production
  </label>
</div>
```

What this code accomplishes is when we have at least one selected checkbox the Phoenix controller receives an array like `["ci", "staging"]` that Ecto does understand, and when there is none selected it receives an empty string that Ecto does transform automatically into an empty array when creating the Changeset.

I've `IO.inspect`'ed a bit into the library code and it seams like the multiple tags are not merged, probably because the name differ(with and without `[]`), and the checkbox tags are simply ignored.

If we change the name of the hidden field to match the other inputs this error is fixed, but the functionality is broken since it will actually always send the empty string as the first element of the array(`["", "ci", "staging"]`) and Ecto does not understand that.

I could remove the first element of the array, but that would require also changing a lot of validations around it, and it feels wrong to change so much battle tested production code to fix a test.

Any other ideas on how I could fix this while keeping the same behaviour?
Or could it be possible to backport #42 to 0.7.x in order to have it compatible with phoenix 1.5?

**Comment by marick** [comment]
I'll try to take a look at this tomorrow.

**Comment by marick** [comment]
I'm trying to reproduce this. What should happen is that the `hidden` <input> gets overwritten by the later ones, so the final tree from the form looks like this:

```elixir
  tree: %{
    ab_test: %{
      environments: %PhoenixIntegration.Form.Tag{
        checked: true,
        has_list_value: true,
        name: "ab_test[environments][]",
        original: {...},
        path: [:ab_test, :environments],
        tag: "input",
        type: "checkbox",
        values: ["ci", "staging"]
      }
    }
  },
```

... and then a `follow_form` with a `%{ab_test: %{environments: ["ci"]}}` second argument would work. That's what happens when I pasted the form you gave into a test code. 

Could you do this:

1. Clone https://github.com/marick/phoenix_integration
2. `mix test`
3. That runs a test over the form you gave above. If the test passes, can you take more of your HTML and put it in `test/fixtures/templates/checkbox.html `, replacing [what's there now](https://github.com/marick/phoenix_integration/blob/master/test/fixtures/templates/checkbox.html#L17)? Be careful to leave the `id` of the form alone or change the id used in [the test](https://github.com/marick/phoenix_integration/blob/master/test/checkbox_test.exs#L15)
4. Repeat until the last value printed is `{:error, ...}`.

Thanks.

---------

```elixir
......form as read: {"form",
 [
   {"accept-charset", "UTF-8"},
   {"action", "/form"},
   {"id", "issue45"},
   {"method", "post"}
 ],
 [
   {"div", [],
    [
      {"input",
       [
         {"id", "ab_test_environments"},
         {"name", "ab_test[environments]"},
         {"type", "hidden"},
         {"value", ""}
       ], []},
      {"label", [{"class", "checkbox-inline"}],
       [
         {"input",
          [
            {"data-persisted", "false"},
            {"name", "ab_test[environments][]"},
            {"type", "checkbox"},
            {"value", "ci"},
            {"checked", ""}
          ], []},
         "\n    Ci\n  "
       ]},
      {"label", [{"class", "checkbox-inline"}],
       [
         {"input",
          [
            {"data-persisted", "false"},
            {"name", "ab_test[environments][]"},
            {"type", "checkbox"},
            {"value", "staging"},
            {"checked", ""}
          ], []},
         "\n    Staging\n  "
       ]},
      {"label", [{"class", "checkbox-inline"}],
       [
         {"input",
          [
            {"data-persisted", "false"},
            {"name", "ab_test[environments][]"},
            {"type", "checkbox"},
            {"value", "production"}
          ], []},
         "\n    Production\n  "
       ]}
    ]}
 ]}
form converted to a tree: %PhoenixIntegration.Form.TreeCreation{
  errors: [],
  tree: %{
    ab_test: %{
      environments: %PhoenixIntegration.Form.Tag{
        checked: true,
        has_list_value: true,
        name: "ab_test[environments][]",
        original: {"input",
         [
           {"data-persisted", "false"},
           {"name", "ab_test[environments][]"},
           {"type", "checkbox"},
           {"value", "ci"},
           {"checked", ""}
         ], []},
        path: [:ab_test, :environments],
        tag: "input",
        type: "checkbox",
        values: ["ci", "staging"]
      }
    }
  },
  valid?: true,
  warnings: []
}
edited tree: {:ok,
 %{
   ab_test: %{
     environments: %PhoenixIntegration.Form.Tag{
       checked: true,
       has_list_value: true,
       name: "ab_test[environments][]",
       original: {"input",
        [
          {"data-persisted", "false"},
          {"name", "ab_test[environments][]"},
          {"type", "checkbox"},
          {"value", "ci"},
          {"checked", ""}
        ], []},
       path: [:ab_test, :environments],
       tag: "input",
       type: "checkbox",
       values: ["ci"]
     }
   }
 }}
```

**Comment by rafaelgaspar** [comment]
Hi @marick, thank you very much for the help, I was able to use your debug test to figure out what was wrong.

Turns out it had nothing to do with the hidden hack, but the `input` tags were not closed(`/>`) in the real code and that made them be ignored, not the naming like I thought.

Thanks for the help.

**Comment by marick** [comment]
Is this a problem with Floki? (I realize that browsers try to make sense of most anything; don't know if Floki makes the same promise.)
