### ISSUE TITLE
Failed to use "phoenix" (version 1.3.0-rc.0) because

### ISSUE THREAD

**Issue by MatUrbanski** [boydm/phoenix_integration#8]
I'm not able to use this library with phoenix 1.3.0-rc.0. I've get the following error when running `mix deps.get`:
```
Failed to use "phoenix" (version 1.3.0-rc.0) because
  phoenix_integration (version 0.2.0) requires ~> 1.1 *
  phoenix_live_reload (version 1.0.8) requires ~> 1.0 or ~> 1.2-rc
  mix.lock specifies 1.3.0-rc.0

* This requirement does not match pre-releases. To match pre-releases include a pre-release in the requirement, such as: "~> 2.0-beta".

** (Mix) Hex dependency resolution failed, relax the version requirements of your dependencies or unlock them (by using mix deps.update or mix deps.unlock). If you are unable to resolve the conflicts you can try overriding with {:dependency, "~> 1.0", override: true}
```

**Comment by boydm** [comment]
You should mark phoenix with the override: true option until the integration library is updated. This will resolve the same issue with several other libraries as well. My deps list looks like this...

      {:phoenix, "~> 1.3.0-rc", override: true},

Having said that, I'm starting the process of updating phoenix_integration (and policy_wonk) for better phoenix 1.3 happiness. If you use phoenix 1.3 in a single app, then all is good and it should just work.

If you want to start using phoenix as an umbrella app with multiple websites in it, then the integration library will clearly work in one (I'm doing it now), but may not work with others if they have their own endpoints.

I'm not sure yet how to have phoenix_integration work with multiple phoenix endpoints in a single umbrella application, so solving that may take a bit. If you aren't doing that, then no worries!

**Comment by MatUrbanski** [comment]
Thanks for a quick response!
