### ISSUE TITLE
 ** (RuntimeError) no @endpoint set in test case

### ISSUE THREAD

**Issue by MatUrbanski** [boydm/phoenix_integration#9]
I'm trying to use it in Phoenix 1.3.0-rc.0. I've added `integration_case.ex` to my `test/support` folder:
```
defmodule MyApp.Web.IntegrationCase do
  use ExUnit.CaseTemplate

  using do
    quote do
      use MyApp.Web.ConnCase
      use PhoenixIntegration
    end
  end
end

```

and I wrote simple spec which look like this:

```
defmodule MyApp.AboutIntegrationTest do
  use MyApp.Web.IntegrationCase, async: true

  setup do
    conn = build_conn()
    {:ok, conn: conn}
  end

  test "Basic page flow", %{conn: conn} do
    get( conn, project_path(conn, :index) )
    |> follow_link( "MyApp )
    |> assert_response( status: 200, path: project_path(conn, :index) )
  end
end

```
When I try to run specs it returns me following error:

```
  1) test Basic page flow (MyApp.AboutIntegrationTest)
     test/integrations/first_test.exs:9
     ** (RuntimeError) no @endpoint set in test case
     stacktrace:
       (phoenix) lib/phoenix/test/conn_test.ex:214: Phoenix.ConnTest.dispatch/5
       (phoenix_integration) lib/phoenix_integration/requests.ex:233: PhoenixIntegration.Requests.follow_link/3
       test/integrations/first_test.exs:11: (test)

```

What I'm doing wrong?

**Comment by boydm** [comment]
Is this an umbrella app?

I'm getting started using it in phoenix 1.3 too.

Check your MyApp.ConCase file. Make sure that @endpoint is set there. Like this

```
  using do
    quote do
      # Import conveniences for testing with connections
      use Phoenix.ConnTest
      import MyApp.Router.Helpers

      # The default endpoint for testing
      @endpoint MyApp.Endpoint

    end
  end
```

**Comment by MatUrbanski** [comment]
No this is not an umbrella app, this is standalone phoenix app. `MyApp.ConnCase` seems to be  correct:

```
defmodule MyApp.Web.ConnCase do
  use ExUnit.CaseTemplate

  using do
    quote do
      use Phoenix.ConnTest
      import MyApp.Web.Router.Helpers

      @endpoint MyApp.Web.Endpoint
    end
  end


  setup tags do
    :ok = Ecto.Adapters.SQL.Sandbox.checkout(MyApp.Repo)
    unless tags[:async] do
      Ecto.Adapters.SQL.Sandbox.mode(MyApp.Repo, {:shared, self()})
    end
    {:ok, conn: Phoenix.ConnTest.build_conn()}
  end
end

```

**Comment by boydm** [comment]
Try this.

on the command line...

mix deps.clean phoenix_integration
mix deps.get

Then re-run your tests.

I know this is weird, but when you change (or set) the @endpoint, the compiler doesn't immediately recompile the deps that may be affected by it. I've had this issue with a few other packages as well and I forget every time. Am trying to think of a better way to do this.

**Comment by MatUrbanski** [comment]
Great answer. Now everything works as expected :+1:

**Comment by boydm** [comment]
Oh wait. You have to set the endpoint in your test.exs config file. I should have remembered that.

config :phoenix_integration, endpoint: MyApp.Endpoint

That's the one that if it changes, you have to recompile the package.

**Comment by adrianmancuso** [comment]
@boydm I'm encountering a similar issue when attempting to deploy to a staging environment via buildkite.  Everything is working as expected locally and I have `config :phoenix_integration, endpoint: MyAppWeb.Endpoint` in `test.exs`.

MyAppWeb.IntegrationCase : 
```  
using do
    quote do
      use MyAppWeb.ConnCase
      use PhoenixIntegration
      import MyAppWeb.IntegrationCase.Helpers
    end
  end
```

MyAppWeb.ConnCase : 
```
  use ExUnit.CaseTemplate

  using do
    quote do
      # Import conveniences for testing with connections
      use Phoenix.ConnTest
      import MyAppWeb.Router.Helpers

      # The default endpoint for testing
      @endpoint MyAppWeb.Endpoint
    end
  end
```

Despite this every test fails:
```

1) test successful user flow (MyAppWeb.UserFlowTest)
--
test/myapp_web/integration/user_flow_test.exs:4
     ** (RuntimeError) no @endpoint set in test case
     code: |> follow_form(%{key: "value", password: "password"})
     stacktrace:
       (phoenix) lib/phoenix/test/conn_test.ex:214: Phoenix.ConnTest.dispatch/5
       (phoenix_integration) lib/phoenix_integration/requests.ex:496: PhoenixIntegration.Requests.follow_form/3
test/myapp_web/integration/user_flow_test.exs:9: (test)

```

Any ideas what could be causing this?

**Comment by boydm** [comment]
Hmmm. Off the top of my head, I don't know and haven't used buildkite yet...

Does it use the same test configuration as your local version?

**Comment by adrianmancuso** [comment]
Yep, it's exactly the same 😕

**Comment by fredwu** [comment]
Just a quick note in case anyone else run into this same issue:

We run in a dockerised environment and had some funkiness in terms of the way we copy files from host to container, and the order of compilation. The result was that we were compiling the dependencies (including phoenix_integration) before our app files are copied. Once that's addressed, this problem went away. :)

**Comment by boydm** [comment]
Thank you Fred! That sounds like the culprit for Adrian.

Adrian, please take a look at the build order. After your config files get loaded, you may need to force phoenix_integration to recompile.
